# Generated by Django 2.2 on 2019-10-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
        ('events', '0001_initial'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_records', to='products.BatchInfo')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('complete_status', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_outlet', to='outlets.Outlet')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='products.Product')),
                ('sending_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_outlet', to='outlets.Outlet')),
                ('stock_transfer_record', models.ManyToManyField(related_name='stock_transfer_record', to='stock.StockTransferRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCountTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Scheduled in advance', max_length=50)),
                ('is_closed', models.BooleanField(default=False)),
                ('interval', models.PositiveIntegerField(blank=True, null=True)),
                ('end_on', models.DateField(blank=True, null=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('assigned_users', models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('batches', models.ManyToManyField(blank=True, related_name='batches_to_count', to='products.BatchInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designated_users', models.ManyToManyField(related_name='designated_to', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='outlets.Outlet')),
                ('products', models.ManyToManyField(related_name='products_to_count', to='products.Product')),
                ('schedule_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='StockCountRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('quantity_counted', models.PositiveIntegerField(blank=True, null=True)),
                ('batch_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.BatchInfo')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('variance_reason', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('stock_count_record', models.ManyToManyField(related_name='stock_count_record', to='stock.StockCountRecord')),
                ('stock_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockCountTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='stockcounttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(unique=True), fields=('created_at', 'interval', 'end_on', 'created_by'), name='unique_template_user'),
        ),
    ]
