# Generated by Django 2.2 on 2019-10-07 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=244, unique=True)),
                ('symbol', models.CharField(max_length=244)),
                ('symbol_native', models.CharField(max_length=244)),
                ('decimal_digits', models.IntegerField()),
                ('rounding', models.IntegerField()),
                ('code', models.CharField(max_length=244, unique=True)),
                ('name_plural', models.CharField(max_length=244)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0.0)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=244, unique=True)),
                ('time_zone', models.CharField(max_length=244, unique=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_preference', models.BooleanField(default=False)),
                ('barcode_preference', models.BooleanField(default=False)),
                ('reorder_point', models.IntegerField(default=3)),
                ('reorder_max', models.IntegerField(default=6)),
                ('retain_user', models.BooleanField(default=True)),
                ('sales_hold', models.IntegerField(default=7)),
                ('alert_low_inventory', models.BooleanField(default=False)),
                ('alert_near_expiry', models.BooleanField(default=False)),
                ('weeks_to_start_supply_alert', models.IntegerField(default=1)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('minimum_weeks_for_sales_velocity', models.IntegerField(default=1)),
                ('sales_velocity', models.IntegerField(default=1)),
                ('returnable_days', models.IntegerField(default=30)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
                ('outlet_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference.Currency')),
                ('outlet_timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference.Timezone')),
                ('vat_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference.Vat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_preference', models.BooleanField(default=False)),
                ('barcode_preference', models.BooleanField(default=False)),
                ('reorder_point', models.IntegerField(default=3)),
                ('reorder_max', models.IntegerField(default=6)),
                ('retain_user', models.BooleanField(default=True)),
                ('sales_hold', models.IntegerField(default=7)),
                ('alert_low_inventory', models.BooleanField(default=False)),
                ('alert_near_expiry', models.BooleanField(default=False)),
                ('weeks_to_start_supply_alert', models.IntegerField(default=1)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('minimum_weeks_for_sales_velocity', models.IntegerField(default=1)),
                ('sales_velocity', models.IntegerField(default=1)),
                ('returnable_days', models.IntegerField(default=30)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
