# Generated by Django 2.1.7 on 2019-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0005_auto_20190625_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletpreference',
            name='outlet',
        ),
        migrations.AlterField(
            model_name='businesspreference',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='outletpreference',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
