# Generated by Django 2.2 on 2019-10-07 14:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import healthid.utils.app_utils.id_generator
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_received', models.DateField()),
                ('expiry_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('sold_out', models.BooleanField(default=False)),
                ('is_returnable', models.BooleanField(default=True)),
                ('service_quality', models.PositiveIntegerField(default=3)),
                ('delivery_promptness', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('survey_closed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_price_surveys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_price_surveys', to='outlets.Outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('quantity_received', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('request_declined', models.BooleanField(default=False)),
                ('comment', models.TextField(null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_user', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_quantities', to='products.BatchInfo')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposedQuantityChange', to='products.Quantity')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposing_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('amount_paid', models.PositiveIntegerField(default=100)),
                ('loyalty_weight', models.PositiveIntegerField(default=0)),
                ('markup', models.PositiveIntegerField(default=25)),
                ('is_vat_applicable', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
            ],
            options={
                'unique_together': {('name', 'outlet')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=244)),
                ('sku_number', models.CharField(max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('vat_status', models.BooleanField(default=False)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('nearest_expiry_date', models.DateField(null=True)),
                ('admin_comment', models.TextField(null=True)),
                ('markup', models.PositiveIntegerField(default=25)),
                ('auto_price', models.BooleanField(default=True)),
                ('loyalty_weight', models.IntegerField(default=0)),
                ('is_returnable', models.BooleanField(default=True)),
                ('image', models.URLField(default='https://res.cloudinary.com/dojaopytm/image/upload/v1558444184/productPlaceholder.png')),
                ('is_active', models.BooleanField(default=True)),
                ('reorder_point', models.IntegerField(default=0)),
                ('reorder_max', models.IntegerField(default=0)),
                ('request_declined', models.BooleanField(default=False)),
                ('backup_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='orders.Suppliers')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MeasurementUnit')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_products', to='outlets.Outlet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposedEdit', to='products.Product')),
                ('preferred_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefered', to='orders.Suppliers')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product_name', 'manufacturer', 'outlet', 'description', 'measurement_unit')},
            },
            managers=[
                ('all_products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceCheckSurvey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_checks', to='products.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='orders.Suppliers')),
                ('survey', models.ManyToManyField(related_name='survey_price_checks', to='products.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_info', to='products.Product'),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers'),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
