# Generated by Django 2.1.7 on 2019-05-23 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_closed'),
        ('products', '0008_auto_20190515_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPromptness',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='batchinfo',
            old_name='commentary',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='service_quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='sku_number',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='delivery_promptness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DeliveryPromptness'),
            preserve_default=False,
        ),
    ]
