# Generated by Django 2.1.7 on 2019-05-15 11:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
        ('outlets', '0004_outlet_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20190509_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCheckSurvey',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_checks', to='products.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='orders.Suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('survey_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_price_surveys', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_price_surveys', to='outlets.Outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pricechecksurvey',
            name='survey',
            field=models.ManyToManyField(related_name='survey_price_checks', to='products.Survey'),
        ),
    ]
