# Generated by Django 2.1.7 on 2019-06-18 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_auto_20190530_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPromptness',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='batchinfo',
            old_name='commentary',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='service_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='delivery_promptness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DeliveryPromptness'),
            preserve_default=False,
        ),
    ]
