# Generated by Django 2.2 on 2019-12-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20191212_1729'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchinfo',
            constraint=models.UniqueConstraint(fields=('batch_no',), name='unique_batch_no'),
        ),
    ]
