steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/healthid', '.']
    env:
    - 'SECRET=${_SECRET}'
    - 'DEBUG=${_DEBUG}'
    - 'PASSWORD=${_PASSWORD}'
    - 'EMAIL_HOST=${_EMAIL_HOST}'
    - 'EMAIL_USE_TLS=${_EMAIL_USE_TLS}'
    - 'EMAIL_PORT=${_EMAIL_PORT}'
    - 'EMAIL_HOST_USER=${_EMAIL_HOST_USER}'
    - 'EMAIL_HOST_PASSWORD=${_EMAIL_HOST_PASSWORD}'
    - 'DEFAULT_FROM_EMAIL=${_DEFAULT_FROM_EMAIL}'
    - 'DOMAIN=${_DOMAIN}'
    - 'CLOUD_NAME=${_CLOUD_NAME}'
    - 'API_KEY=${_API_KEY}'
    - 'API_SECRET=${_API_SECRET}'
    - 'FRONTEND_URL=${_FRONTEND_URL}'
    - 'PUSHER_APP_ID=${_PUSHER_APP_ID}'
    - 'PUSHER_KEY=${_PUSHER_KEY}'
    - 'PUSHER_SECRET=${_PUSHER_SECRET}'
    - 'PUSHER_CLUSTER=${_PUSHER_CLUSTER}'
    - 'DB_NAME=${_DB_NAME}'
    - 'DB_USER=${_DB_USER}'
    - 'DB_PASSWORD=${_DB_PASSWORD}'
    - 'HOST=${_HOST}'

images:
  - 'gcr.io/$PROJECT_ID/healthid'