# Generated by Django 2.2 on 2019-10-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('trading_name', models.CharField(max_length=244)),
                ('legal_name', models.CharField(max_length=244, unique=True)),
                ('address_line_1', models.CharField(blank=True, max_length=244)),
                ('address_line_2', models.CharField(blank=True, max_length=244)),
                ('local_government_area', models.CharField(blank=True, max_length=244)),
                ('country', models.CharField(blank=True, max_length=244)),
                ('city', models.CharField(blank=True, max_length=244)),
                ('phone_number', models.CharField(max_length=25)),
                ('business_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('website', models.CharField(max_length=344)),
                ('facebook', models.CharField(max_length=344)),
                ('twitter', models.CharField(max_length=344)),
                ('instagram', models.CharField(max_length=244)),
                ('logo', models.URLField()),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
