# Generated by Django 2.2 on 2019-10-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '__first__'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('cashier', models.BooleanField(default=True)),
                ('discount_total', models.BooleanField(default=True)),
                ('receipt_no', models.BooleanField(default=True)),
                ('receipt', models.BooleanField(default=True)),
                ('subtotal', models.BooleanField(default=True)),
                ('total_tax', models.BooleanField(default=True)),
                ('amount_to_pay', models.BooleanField(default=True)),
                ('purchase_total', models.BooleanField(default=True)),
                ('change_due', models.BooleanField(default=True)),
                ('loyalty', models.BooleanField(default=True)),
                ('loyalty_earned', models.BooleanField(default=True)),
                ('loyalty_balance', models.BooleanField(default=True)),
                ('barcode', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=50, null=True)),
                ('barcode_url', models.URLField(null=True)),
                ('scanned_number', models.BigIntegerField(null=True)),
                ('footer', models.CharField(default='Thank you for shopping with us.', max_length=244)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.ReceiptTemplate')),
                ('sale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
                ('sales_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.SaleReturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
