# Generated by Django 2.1.7 on 2019-03-28 11:37

from django.db import migrations, models
import django.db.models.deletion
import healthid.apps.outlets.models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(default=healthid.apps.outlets.models.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('cashier', models.CharField(max_length=244)),
                ('discount', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('amount_to_pay', models.IntegerField()),
                ('purchase_total', models.IntegerField()),
                ('change_due', models.IntegerField()),
                ('loyal', models.IntegerField()),
            ],
            options={
                'ordering': ('cashier',),
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Receipt')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
