# Generated by Django 2.1.7 on 2019-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_outlet_user'),
        ('outlets', '0002_receipt_register'),
    ]

    operations = [
    ]
