# Generated by Django 2.1.7 on 2019-03-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_auto_20190328_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='assigned_outlet',
            new_name='outlet',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='assigned_receipt',
            new_name='receipt',
        ),
    ]
