# Generated by Django 2.1.7 on 2019-04-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_merge_20190408_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipttemplates', to='receipts.ReceiptTemplate'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
