# Generated by Django 2.1.7 on 2019-04-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_auto_20190408_1636'),
        ('receipts','__latest__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipttemplate', to='receipts.ReceiptTemplate'),
        ),
    ]
