# Generated by Django 2.1.7 on 2019-04-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0006_auto_20190408_1639'),
        ('outlets', '0004_auto_20190329_0252'),
    ]

    operations = [
    ]
