# Generated by Django 2.2 on 2019-10-07 14:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '__first__'),
        ('profiles', '__first__'),
        ('business', '0001_initial'),
        ('events', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('approved_delivery_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('In_Person', 'In Person'), ('Telephonic', 'Telephonic'), ('Video_Conferencing', 'Video Conferencing')], default='In_Person', max_length=50), size=None)),
                ('consultant_role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Health_Coach', 'Health Coach'), ('Pharmacist', 'Pharmacist'), ('Sales_Person', 'Sales Associate')], default='Pharmacist', max_length=20)),
                ('minutes_per_session', models.IntegerField()),
                ('price_per_session', models.IntegerField()),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_catalogue', to='business.Business')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('consultation_name', 'business', 'approved_delivery_formats', 'minutes_per_session')},
            },
        ),
        migrations.CreateModel(
            name='CustomerConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consultant', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Now', 'Now'), ('Done', 'Already Completed'), ('Later', 'Later')], default='Now', max_length=10)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by_user', to=settings.AUTH_USER_MODEL)),
                ('consultation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_consultations', to='consultation.ConsultationCatalogue')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_event', to='events.Event')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_consultations', to='outlets.Outlet')),
                ('sale_record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_sale_record', to='sales.Sale')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_consultation_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medical_notes', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_authorizations', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.CustomerConsultation')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
